title: 个性化设置中心
subtitle: 调整账户、安全策略与遗忘引擎偏好，让忆滤真正符合你的思维节奏。
badge:
  label: 设置中心
  color: primary
  icon: i-lucide-settings
sections:
  - key: account
    title: 账户与安全
    description: 管理账户资料、登录方式与安全策略。
    icon: i-lucide-user-round
    cards:
      - key: profile
        title: 基本资料
        description: 更新个人信息以便 AI 更好地理解你的语境。
        icon: i-lucide-badge-check
        type: profile
        fields:
          - key: displayName
            label: 显示名称
            placeholder: 输入你的昵称
            helper: 将用于注释与记忆摘要的署名。
            type: text
          - key: email
            label: 登录邮箱
            placeholder: name@example.com
            helper: 邮箱将作为登录凭据与通知渠道。
            type: email
      - key: security
        title: 安全保护
        description: 通过更严格的策略守护记忆资产。
        icon: i-lucide-shield-check
        type: security
        toggles:
          - key: twoFactor
            label: 启用双重验证
            description: 登录时额外需要一次性验证码，增强账号安全。
            icon: i-lucide-shield-alert
            default: true
          - key: deviceAlerts
            label: 新设备登录提醒
            description: 当有新设备访问你的账户时立即推送提醒。
            icon: i-lucide-smartphone-nfc
            default: true
  - key: preferences
    title: 遗忘引擎偏好
    description: 定制遗忘节奏、保留阈值与 AI 辅助功能。
    icon: i-lucide-brain-circuit
    cards:
      - key: memoryEngine
        title: 遗忘节奏
        description: 控制遗忘引擎的默认强度与节奏。
        icon: i-lucide-timer
        type: select-group
        options:
          - key: balanced
            label: 均衡模式
            description: 结合重要度与时间，自动调整遗忘速度。
          - key: aggressive
            label: 加速遗忘
            description: 更积极地压缩低价值信息，保持知识库精简。
          - key: gentle
            label: 温和遗忘
            description: 延长笔记保留期，适合长期复习。
      - key: aiAssist
        title: AI 辅助
        description: 控制 AI 整理与总结的触发方式。
        icon: i-lucide-sparkles
        type: toggle-group
        toggles:
          - key: autoSummaries
            label: 自动生成遗忘摘要
            description: 在笔记淡化前自动输出一份浓缩摘要，支持回顾。
            icon: i-lucide-wand-2
            default: true
          - key: relevanceScan
            label: 关联性扫描
            description: 当内容被标记为噪声时，自动检索与其相关的高价值笔记。
            icon: i-lucide-scan
            default: false
  - key: notifications
    title: 提醒与日志
    description: 配置每日 digest、关键事件提醒与操作日志。
    icon: i-lucide-bell-ring
    cards:
      - key: digest
        title: 每日 Digest
        description: 选择每日摘要的时间窗口。
        icon: i-lucide-calendar-clock
        type: select-group
        options:
          - key: morning
            label: 08:00 晨间回顾
            description: 适合在开始一天前整理记忆。
          - key: noon
            label: 12:30 午间更新
            description: 在午休时快速浏览最新变化。
          - key: evening
            label: 20:00 晚间整理
            description: 睡前回顾当天的遗忘与保留。
      - key: alerts
        title: 关键事件提醒
        description: 控制系统对重要事件的推送。
        icon: i-lucide-bell-plus
        type: toggle-group
        toggles:
          - key: collapseAlerts
            label: 折叠事件提醒
            description: 当笔记临近折叠或被自动清理时推送通知。
            icon: i-lucide-fold-horizontal
            default: true
          - key: recoveryAlerts
            label: 恢复窗口提醒
            description: 提前提醒可恢复的遗忘内容即将过期。
            icon: i-lucide-inbox
            default: true
          - key: experimentAlerts
            label: 实验功能更新
            description: 推送遗忘引擎新策略与实验功能的更新提醒。
            icon: i-lucide-flask
            default: false
